-- =============================================
-- 126: MASTER CODES, MULTIPLE RATE TYPES, RATE CATEGORY ITEMS,
--      DISCOUNT CATEGORY RULES
--
-- 1. Master codes - generated by the system and shown read-only on the
--    create form: <fiscal year><sep><TYPE><running number>, e.g.
--    8182LDG000001 (ledger) or 8182-PRD0000001 (product). Each master has
--    its own counter per fiscal year (restarts every year). TYPE /
--    separator / digits per master: system_control_settings.master_code_format
--    (server/utils/masterCodes.js has the defaults).
-- 2. Multiple Rate Type - the five fixed sales-rate columns Sr1..Sr5 get a
--    caption (e.g. "Whole Sell Rate") and an on / off switch; Product Master
--    shows only the enabled ones, labelled with the caption.
-- 3. Rate Category - besides the Sr tier, a category can list its own
--    product + unit + rate (unlimited rows); those win over the tier.
-- 4. Discount Category (discount_groups) - payment term, "effect on rate"
--    and rules: product + unit, Qty or Value slab From..To, then %, rate
--    off per qty or a fixed amount. The company matrix stays as it was.
-- Nothing existing is removed or renamed.
-- =============================================

-- 1. master codes ------------------------------------------------------
ALTER TABLE tenant_master.system_control_settings
    ADD COLUMN IF NOT EXISTS master_code_format JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS tenant_master.master_code_counters (
    tenant_id UUID NOT NULL,
    master VARCHAR(40) NOT NULL,
    fy VARCHAR(8) NOT NULL DEFAULT '',
    last_no BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (tenant_id, master, fy)
);

-- takes the next number atomically (row lock of the upsert)
CREATE OR REPLACE FUNCTION tenant_master.next_master_no(p_tenant_id UUID, p_master TEXT, p_fy TEXT DEFAULT '')
RETURNS BIGINT AS $$
DECLARE n BIGINT;
BEGIN
  INSERT INTO tenant_master.master_code_counters AS m (tenant_id, master, fy, last_no, updated_at)
  VALUES (p_tenant_id, p_master, COALESCE(p_fy, ''), 1, NOW())
  ON CONFLICT (tenant_id, master, fy) DO UPDATE SET last_no = m.last_no + 1, updated_at = NOW()
  RETURNING last_no INTO n;
  RETURN n;
END; $$ LANGUAGE plpgsql;

-- 2. rate types ------------------------------------------------------------
ALTER TABLE tenant_master.system_control_settings
    ADD COLUMN IF NOT EXISTS rate_types JSONB NOT NULL DEFAULT '[
      {"sr": 1, "caption": "Whole Sell Rate", "enabled": true},
      {"sr": 2, "caption": "Distributor Rate", "enabled": true},
      {"sr": 3, "caption": "Retail Rate", "enabled": true},
      {"sr": 4, "caption": "Special Rate", "enabled": false},
      {"sr": 5, "caption": "Custom Rate", "enabled": false}
    ]'::jsonb;

-- auto billing may use any of the five rate types, not only Sr1 / Sr2
ALTER TABLE tenant_master.system_control_settings DROP CONSTRAINT IF EXISTS valid_auto_billing_rate_type;
ALTER TABLE tenant_master.system_control_settings ADD CONSTRAINT valid_auto_billing_rate_type
    CHECK (auto_billing_rate_type IN ('sr1', 'sr2', 'sr3', 'sr4', 'sr5', 'mrp'));

-- 3. rate category rows ------------------------------------------------------
ALTER TABLE tenant_master.rate_categories ADD COLUMN IF NOT EXISTS description TEXT;

CREATE TABLE IF NOT EXISTS tenant_master.rate_category_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    rate_category_id UUID NOT NULL REFERENCES tenant_master.rate_categories(id) ON DELETE CASCADE,
    serial_no INTEGER NOT NULL DEFAULT 1,
    product_id UUID NOT NULL REFERENCES tenant_master.products(id) ON DELETE CASCADE,
    unit_id UUID REFERENCES tenant_master.product_units(id),
    rate DECIMAL(15, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT valid_rate_category_item_rate CHECK (rate >= 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_rate_category_item ON tenant_master.rate_category_items(rate_category_id, product_id, COALESCE(unit_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS idx_rate_category_items_lookup ON tenant_master.rate_category_items(tenant_id, rate_category_id, product_id);

-- 4. discount category -----------------------------------------------------------
ALTER TABLE tenant_master.discount_groups ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tenant_master.discount_groups ADD COLUMN IF NOT EXISTS payment_term VARCHAR(20) NOT NULL DEFAULT 'any';
ALTER TABLE tenant_master.discount_groups ADD COLUMN IF NOT EXISTS effect_on_rate BOOLEAN NOT NULL DEFAULT FALSE;
DO $$ BEGIN
  ALTER TABLE tenant_master.discount_groups ADD CONSTRAINT valid_discount_group_payment_term
    CHECK (payment_term IN ('any', 'cash', 'credit', 'credit_15', 'credit_30', 'credit_60', 'advance'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS tenant_master.discount_group_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    discount_group_id UUID NOT NULL REFERENCES tenant_master.discount_groups(id) ON DELETE CASCADE,
    serial_no INTEGER NOT NULL DEFAULT 1,
    product_id UUID REFERENCES tenant_master.products(id) ON DELETE CASCADE,
    unit_id UUID REFERENCES tenant_master.product_units(id),
    basis VARCHAR(10) NOT NULL DEFAULT 'qty',
    from_value DECIMAL(15, 4) NOT NULL DEFAULT 0,
    to_value DECIMAL(15, 4),
    discount_percent DECIMAL(7, 4),
    rate_per_qty DECIMAL(15, 4),
    fixed_amount DECIMAL(15, 2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT valid_discount_rule_basis CHECK (basis IN ('qty', 'value')),
    CONSTRAINT valid_discount_rule_range CHECK (from_value >= 0 AND (to_value IS NULL OR to_value >= from_value)),
    CONSTRAINT valid_discount_rule_percent CHECK (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100)),
    CONSTRAINT valid_discount_rule_amounts CHECK (COALESCE(rate_per_qty, 0) >= 0 AND COALESCE(fixed_amount, 0) >= 0),
    CONSTRAINT discount_rule_has_one_benefit CHECK (
        (CASE WHEN COALESCE(discount_percent, 0) > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN COALESCE(rate_per_qty, 0) > 0 THEN 1 ELSE 0 END) +
        (CASE WHEN COALESCE(fixed_amount, 0) > 0 THEN 1 ELSE 0 END) = 1)
);
CREATE INDEX IF NOT EXISTS idx_discount_group_rules_lookup ON tenant_master.discount_group_rules(tenant_id, discount_group_id, product_id);

-- audit the new tables like every other table (migration 123)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'audit_attach_all') THEN PERFORM tenant_master.audit_attach_all(); END IF;
END $$;
