# -*- coding: utf-8 -*-
"""Page help - masters, setup, reports, dashboards, tools and the industry
modules (poultry, construction, automobile)."""
from help_pages_entry import ALL

RO = dict(accounts='None - read only.', stock='None - read only.', vat='None.')


def R(path, title, module, purpose, how, views=None, nature=None, tips=None):
    """a report page"""
    return dict(path=path, title=title, module=module, kind='report', nature=nature or ALL, purpose=purpose,
                steps=how, views=views or {}, tips=tips or [], **RO)


def M(path, title, module, purpose, steps, other='', nature=None, tips=None, accounts='None.', stock='None.', vat='None.'):
    """a master / setup page"""
    return dict(path=path, title=title, module=module, kind='master', nature=nature or ALL, purpose=purpose, steps=steps,
                accounts=accounts, stock=stock, vat=vat, other=other, tips=tips or [])


PAGES = [
    # ================= MASTERS =================
    M('/chart-of-accounts', 'Chart of Accounts (Ledger)', 'Masters',
      'Ledgers and account groups. The group decides where a ledger goes in the Balance Sheet / P&L, ratios and cash flow; the category type decides where it is offered (customer, supplier, cash, bank).',
      ['Ledger Accounts tab: New Ledger Account - name, group, category type, PAN, credit limit / days, bill-wise tracking, opening balance, area / route / agent, rate / discount category.',
       'Account Groups tab: groups with their NFRS classification.', 'Ledger Categories tab: categories for grouping ledgers.'],
      other='Every posting uses these ledgers; the ledger purpose check stops a P&L ledger being used where a Balance Sheet one is needed (and the reverse).',
      accounts='Opening balances are the start of the ledger (Ledger Opening Balance).'),
    M('/sub-ledgers', 'Sub Ledgers', 'Masters', 'Sub-divisions of a ledger (branches of a customer, projects, TDS types ...). Postings carry them for sub-ledger statements and ageing.',
      ['Choose the main ledger, add sub-ledgers with code / name.']),
    M('/cost-profit-centers', 'Cost & Profit Centers', 'Masters', 'Departments, projects, sites, sheds ... that postings are tagged with (P&L by cost center, budgets).',
      ['Cost Centers / Profit Centers tabs: add, set parent for a hierarchy.']),
    M('/billing-terms', 'Billing Terms', 'Masters',
      'VAT, excise, discounts, freight and other charges used on sales / purchase documents - formula, sign (+ / -), basis, ledger, return ledger, sub-ledger, which entries they apply to.',
      ['New Billing Term: name, type (VAT / excise / discount / other), formula or rate, sign, basis (value / quantity), ledgers and sub-ledgers.',
       'Term Used For: Transaction term (Sales / Purchase / Production Entry - on the bill itself) or Additional term (Purchase / Sales Additional - a later bill such as freight, customs, insurance).',
       'Effect: Include In Costing (the amount goes into the cost of the goods / landed cost; off = an expense only), Include In Profitability (counted in the profitability reports) and TDS Applicable + TDS % (the TDS of a Purchase Additional entry is worked out by itself on these terms at this rate; empty % = System Control default).',
       'Product Wise: entered per product (popup per product); otherwise bill-wise, divided over the products by the basis.'],
      other='Term Mapping in System Control decides which term is VAT, discount 1-5, bill discount. VAT terms decide which VAT ledger gets the VAT.'),
    M('/customs-offices', 'Customs Offices (Bhansar)', 'Masters', 'Customs offices picked on import Purchase Bills and on the Customs (Bhansar) tab of Purchase Additional. Nepal\'s customs offices are created with a code the first time the list opens.',
      ['Edit a code / name, add a new office, or deactivate one not used.']),
    M('/remarks-terms', 'Remarks & Terms', 'Masters', 'Saved remarks (narrations) and terms & conditions offered on documents.', ['Add remarks and terms; pick them on entries.']),
    M('/ledger-opening', 'Ledger Opening Balance', 'Masters', 'Opening balances of ledgers on the first day of the opening fiscal year (with bill-wise opening bills).',
      ['Enter Dr / Cr per ledger; party ledgers can have opening bills for bill-wise ageing.'], accounts='Opening balances of the Trial Balance (Dr must equal Cr overall).'),
    M('/products', 'Product Master', 'Masters',
      'Products with units, rates (Sr1-Sr5, purchase), accounts (sales / purchase / return / non-saleable with sub-ledgers), terms, vendor and discount, stock settings (batch, serial, reorder), tracking and rack.',
      ['Basic Info: name, item type (trading, raw material, finished good, service, non-inventory, fixed asset), stock group, company.',
       'Units & Rates: primary unit, other units / dual unit, rates.', 'Account Mapping: product accounts - they come first when posting.',
       'Term Mapping, Vendor & Discount, Stock & Costing, Tracking, Rack Location.'],
      other='Item type service / non-inventory / fixed asset: never moves stock. Product accounts override the document and System Control accounts.'),
    M('/product-units', 'Product Units', 'Masters', 'Units of measure (pcs, box, kg ...), simple or compound.', ['Add the unit name, symbol and type.']),
    M('/product-groups', 'Product Groups & Companies', 'Masters', 'Stock groups and product companies (brands).', ['Product Groups / Product Companies tabs.']),
    M('/categories', 'Categories', 'Masters', 'Product categories for analysis and targets.', ['Add categories.']),
    M('/product-opening', 'Product Opening Stock', 'Masters', 'Opening quantity and rate of products (and opening batches) at the start of the opening fiscal year.',
      ['Enter qty and rate per product / batch / warehouse.'], stock='Opening stock of the stock engine (opening day = day before the fiscal year).'),
    M('/pricing-masters', 'Rate Types, Rate Category, Discount Category', 'Masters',
      'Selling rate types Sr1-Sr5, rate categories (which rate a customer gets) and discount categories.',
      ['Rate Types: names of Sr1-Sr5.', 'Rate Category / Discount Category: add and assign to customers.']),
    M('/product-rate-change', 'Product Rate Change', 'Masters', 'Change selling / purchase rates of many products at once (by % or amount).', ['Filter products, set the change, apply.']),
    M('/product-offer-rate', 'Offer Rate', 'Masters', 'Time-bound offer (scheme) rates for products.', ['Product, rate, from / to dates.']),
    M('/salesman-agents', 'Salesman / Agent', 'Masters', 'Salesmen / agents with commission ledgers, mobile login and order settings.', ['Add the agent, commission expense and payable ledgers, linked user.']),
    M('/route-sequencing', 'Route Sequencing', 'Masters', 'Customers on each route in visiting order.', ['Choose the route, order the customers.']),
    M('/route-plan', 'Route Plan & Mobile Login', 'Masters', 'Which salesman visits which route on which date; mobile app logins.', ['Plan routes by date; give the salesman a user login.']),
    M('/transport-master', 'Transport Master', 'Masters', 'Transporters and vehicles for challans.', ['Add transporter details.']),

    # ================= SETUP =================
    M('/system-control', 'System Control', 'Setup',
      'Company-wide settings: Business Nature (trading, distribution, retail, manufacturing, service, automobile, construction, poultry), default ledgers (VAT, sales, purchase, TDS, cash, bank, GRN clearing, stock), term mapping, number formats, controls (negative stock, credit limit, back / post-date, IRD billing), features (multi warehouse, batch, serial, dual UOM, multi currency).',
      ['Change a setting and Save - it applies to new entries.'],
      other='Business Nature switches the industry menus. IRD Billing locks posted sales bills / returns to cancel-only.'),
    M('/fiscal-years', 'Fiscal Years', 'Setup', 'Fiscal years (Shrawan 1 - Ashadh end), the current year, and closing.',
      ['Add a year; set current.', 'Close: irreversible - nothing dated in a closed year can be posted, cancelled or changed any more.'],
      other='Document numbering restarts per fiscal year.'),
    M('/branches-warehouses', 'Branches & Warehouses', 'Setup', 'Branches and warehouses (stock locations).', ['Branches / Warehouses tabs: add.'],
      stock='Stock is kept per warehouse.'),
    M('/business-units', 'Business Units', 'Setup', 'Divisions / brands / product lines postings are tagged with (P&L by unit).', ['Add units; optional hierarchy.']),
    M('/ledger-mapping', 'Ledger Mapping', 'Setup', 'Which ledgers do which job (sales, purchase, VAT, discount ...) per module.', ['Map each job to a ledger.']),
    M('/document-numbering', 'Document Numbering', 'Setup', 'Number series per document type, fiscal year, branch and category (prefix, digits, reset).',
      ['Add a series: voucher type, prefix, starting number, fiscal year part.'], other='Doc Class Register shows gaps in a series.'),
    M('/currencies', 'Currencies', 'Setup', 'Foreign currencies and exchange rates (Multi Currency).', ['Add currency, symbol and rate.']),
    M('/entry-field-control', 'Entry Field Control', 'Setup', 'Per entry and user: which fields are visible, compulsory, read-only; which pull sources (Quotation / Order / Challan) are offered.',
      ['Choose the entry and user / group; set each field.']),
    M('/user-defined-fields', 'User Defined Fields', 'Setup', 'Extra fields on masters and documents (text, number, date, list).', ['Add the field and the screens it shows on.']),
    M('/users', 'Users', 'Setup', 'Users, their security group, branch, department, rate change limits.', ['New User: email, name, security group, default branch, password.']),
    M('/security-groups', 'Security Groups', 'Setup', 'Rights per module and action (view, create, edit, delete, cancel, approve).', ['Create a group and tick the rights.']),
    M('/data-access', 'Data Access', 'Setup', 'Which ledgers, products, companies, groups, categories and areas a user / group may see.', ['Choose the user / group and allowed items.']),
    M('/audit-log', 'Audit Log', 'Setup', 'Every change with old and new values, user and time; audit coverage of tables.', ['Filter by table, user, date.'], accounts='None - read only.'),
    M('/change-password', 'Change My Password', 'Setup', 'Change your own password.', ['Current password, new password twice.']),
    M('/document-designer', 'Document Designer', 'Setup', 'Print layouts of bills, challans, vouchers, letters, labels.', ['Pick the document type, design fields / layout, set default.']),
    M('/messaging', 'Messaging', 'Setup', 'Email / SMS / WhatsApp / Viber templates, auto-send on posting, message log and bulk outstanding reminders.',
      ['Templates tab: text with placeholders.', 'Auto-send: which document sends which template.', 'Log / Reminders tabs.']),
    M('/notification-settings', 'My Notification Settings', 'Setup', 'Which in-app / email / SMS notifications you receive.', ['Tick the events and channels.']),

    # ================= ACCOUNTS REPORTS =================
    R('/ledger-report', 'Ledger Report', 'Accounts Report', 'Ledger statement of one ledger / sub-ledger: detail, summary (PDC separate) or monthly.',
      ['Choose ledger, period, mode.', 'Click a line to open the document.']),
    R('/party-summary', 'Party Summary', 'Accounts Report', 'Opening, debit, credit, closing of all parties; PDC can be shown separately.', ['Choose party type and period.']),
    R('/control-reports', 'Control Reports', 'Accounts Report', 'Day Book, Cash & Bank Book, master lists, credit exceeded, inactive customers, non-moving items, price list, cancelled / draft documents, master exceptions.',
      ['Choose the view from the menu (deep link) and the filters.']),
    R('/financial-reports', 'Financial Reports', 'Accounts Report', 'Trial Balance, Profit & Loss, Balance Sheet, schedules / notes, ratios, cash flow, funds flow, group mapping, budget vs actual.',
      ['Choose the tab and period; previous-period comparison is available.', 'Closing stock comes from the stock engine (same as the Stock Movement report).']),
    R('/funds-position', 'Net Position of Funds', 'Accounts Report', 'Cash, bank, receivables, payables, PDC and unused limits - net funds available.', ['Choose the as-on date.']),
    R('/outstanding-report', 'Outstanding Report', 'Accounts Report', 'Receivable / payable outstanding by party (bill-wise when tracked).', ['Choose side, as-on date.']),
    R('/ageing', 'Ageing Report', 'Accounts Report', 'Outstanding by age buckets (customer / supplier / delivery / GRN ageing).', ['Choose buckets, as-on date, basis.']),
    R('/bill-wise-ageing-report', 'Bill-wise Ageing', 'Accounts Report', 'Each open bill with its age and due status.', ['Choose party / as-on date.']),
    R('/budgets', 'Budget vs Actual', 'Accounts Report', 'Budget, actual and variance by dimension.', ['Choose the budget and period.']),
    R('/dimension-reports', 'Dimension Reports', 'Accounts Report', 'Ledger + sub-ledger balances, sub-ledger statement, P&L by cost center / unit / branch / doc class, cost center x ledger, monthly trend, doc class number gaps, missing dimensions.',
      ['Choose the preset from the menu and the period.',
       'Ledger + Sub-ledger Balance: every sub-ledger with opening / debit / credit / closing and, after them, the "Ledger balance" row of the ledger (its master opening included).',
       'Filters: Module (Sales, Purchase, Cash / Bank / PDC, Journal / Notes, Inventory / Production, Other), ledger, group, sub-ledger, cost center, unit, branch, document type, doc class, product company.']),
    R('/day-book', 'Day Book (all-in-one)', 'Accounts Report', 'Every voucher of a day or period with cash / credit split, cash & bank book, party-wise credit summary, and totals per agent and per user.',
      ['Choose the dates. No user / agent = the whole business (cash and bank with opening and closing).',
       'User: vouchers entered by that user. Salesman / Agent: that agent\'s sales, returns, receipts (also cash / bank lines of the agent), PDC, credit notes.',
       'Voucher type: any of Sales Bill, Sales Return, Sales Non-saleable Return, Sales Additional, Purchase Bill / Return / Additional, Cash / Bank Receipt, Payment, PDC Received / Issued, Journal, Credit / Debit Note. Party filter; drafts / pending on request.',
       'Show / hide sections: summary, by voucher type, cash & bank, party-wise credit, by agent, by user, voucher list. Print.']),
    R('/vat-reports', 'VAT Reports', 'Accounts Report', 'Sales / Purchase VAT register (bills, returns, notes, additional bills, taxable JVs), monthly summary, Annex 13, VAT return, VAT ledger, TDS report.',
      ['Register: use the book buttons (Sales Book / Purchase Book) or tick document types; view bill / party / item / month / summary.', 'VAT Return: output VAT, input VAT, payable or carry forward, with a GL check.'],
      tips=['Export in English or Nepali headers with BS dates.']),
    R('/tax-reconciliation', 'Reconciliation (VAT / Sales / Purchase / Stock / TDS)', 'Accounts Report',
      'Do the registers and the books agree? Document by document: VAT register vs VAT ledgers, sales register (incl. JV sales, credit notes) vs sales accounts, purchase register (incl. additional bills, JV purchases, debit notes) vs purchase accounts, purchase value vs value put into stock, TDS vs TDS ledgers.',
      ['Overview: Tallied / Not tallied for each check.', 'Open a tab; click Differences / Only in register / Only in books to see why.', 'Add or remove accounts compared with the chips.']),
    R('/ird', 'IRD Compliance / CBMS', 'Accounts Report', 'IRD materialized view, sales book, CBMS sync queue (retry), IRD audit log and CBMS settings.',
      ['See the IRD User Manual in the Help Center.']),
    R('/register', 'Universal Register', 'Accounts Report', 'Every document of every module with status, party, amount.', ['Filter by type, date, status.']),
    R('/lc-bg-dashboard', 'LC / BG / PDC Dashboard', 'Accounts Report', 'LCs, bank guarantees and PDCs with expiry and actions.', ['Act on due items.']),
    R('/pdc-dashboard', 'PDC Dashboard', 'Accounts Report', 'Post-dated cheques due, overdue, cleared, bounced; deposit / clear from here.', ['Choose received / issued and the period.']),
    R('/document-printing', 'Document Print Status', 'Tools', 'Which documents were printed and how many times; print many at once.', ['Filter documents, tick and print.']),

    # ================= SALES / PURCHASE / INVENTORY REPORTS =================
    R('/sales-purchase-analysis', 'Sales / Purchase Analysis', 'Sales/Purchase', 'Sales and purchase by party, item, group, company, agent, area with qty and value.', ['Choose side, grouping and period.']),
    R('/monthly-analysis', 'Monthly Analysis', 'Sales/Purchase', 'Month-wise sales / purchase by item or party.', ['Choose the year and grouping.']),
    R('/profitability', 'Profitability', 'Sales/Purchase', 'Sales value, cost of goods sold (stock engine), gross profit by item / party / bill.', ['Choose the period and valuation method.']),
    R('/rate-history', 'Rate History', 'Sales/Purchase', 'Rates charged / paid per item and party over time.', ['Choose item / party.']),
    R('/product-rate-history', 'Rate & Discount History', 'Sales/Purchase', 'Rate and discount changes per product.', ['Choose the product.']),
    R('/salesman-reports', 'Salesman Reports', 'Sales/Purchase', 'Salesman / route / area net sales, route plan vs visit, not visited, visit log, order register, pending orders, fill rate, product-wise orders.', ['Choose the view and period.']),
    R('/loading-sheet', 'Loading Sheet', 'Sales/Purchase', 'Items to load per vehicle / route from goods delivery and / or sales bills, with the bill summary on the same sheet.',
      ['Choose dates, sources, customer / salesman / area / route / vehicle filters.',
       'Qty views: By UOM mode - fixed dual "5 Crt 2 Pcs · Total 62 Pcs", flexible "5 Crt = 10 Pcs"; base unit; as entered; split into units; one unit.',
       'The Total row gives the qty as entered per unit and the total in base unit (per base unit when items differ), for fixed and flexible items alike.',
       'Print sections: Items, Bill Summary (bill no, customer, route, amounts, received / sign) and Bill x Item - print them together on one sheet.']),
    R('/purchase-register-report', 'Purchase Register (all)', 'Sales/Purchase', 'Lines of requisitions, quotations, orders, GRNs and bills with converted and outstanding qty / amount.', ['Choose the module and filters; Outstanding only.']),
    R('/grn-outstanding-report', 'GRN Outstanding', 'Sales/Purchase', 'GRN lines not yet billed.', ['Filter by vendor and dates.']),
    R('/consignment-cost', 'Consignment Cost / Sales', 'Sales/Purchase', 'Cost and sales of purchase bills with their additional bills; the first view is Consignment Costing (date-wise).',
      ['Choose the dates (and supplier / product).',
       'Consignment Costing view: per bill a header row, its products and a "Bill No Total" row - Qty, Rate, Basic, Add / Less (bill terms), Net Basic, one column per additional term (costing), one per non-additional term (VAT claimable, TDS, not in costing), Total Additional, Total Non-Additional, Net Amount and Cost Rate (landed / qty).',
       'Product-wise additional terms go wholly to their product; bill-wise terms are divided by the term\'s basis (value net of VAT / qty / equal).',
       'Other views: bill-wise, product-wise, ledger summary and mismatches. Export CSV.']),
    R('/daily-register', 'Daily Register (one-page day sheet)', 'Accounts Report', 'The counter\'s paper day sheet filled from posted vouchers: Sales (cash A / credit B), Purchase (C / D), Received / Bank withdraw (E / F), Expenses / Bank deposit (G / H), Return / Exchange (I / J), cash summary, sales / purchase to date, stock and profit.',
      ['Choose the date (or a date range), optionally a user or salesman / agent.',
       'Cash summary: opening cash + A + E - C - G - refunds = expected closing; the books\' closing and the difference (other cash entries such as JV).',
       'Sales / purchase: opening from the fiscal year start to the day before, today, less return, to date; opening / closing stock, gross and net profit of the day.',
       'Cash detail: count the notes (1000 ... 5, coin) - the difference with the books is shown; write the day\'s note. Count and note are kept on this computer per date.',
       'With a user / agent filter only their vouchers are listed; opening / closing cash, stock and profit are left out. Print for signature.']),
    R('/stock-report', 'Stock Report', 'Inventory', 'Stock quantity and value by item / warehouse / batch.', ['Choose the date, grouping and method.']),
    R('/stock-movement', 'Stock Movement', 'Inventory', 'Opening, in and out by module, closing - qty and value (the same engine as the financial statements\' closing stock).', ['Choose period, method, summary / detail.']),
    R('/stock-in-out', 'Stock In / Out (Qty)', 'Inventory', 'Quantity in and out per document.', ['Choose item and period.']),
    R('/stock-valuation', 'Stock Valuation', 'Inventory', 'Closing stock value by FIFO, moving / weighted average, last purchase - batch / serial items by System Control\'s batch / serial costing (e.g. batch-wise: each batch at its own cost, landed cost of Purchase Additional included).',
      ['Choose the date and method; item + batch shows each batch\'s value. A tag on the item shows when batch / serial costing replaced the method.']),
    R('/stock-ageing', 'Stock Ageing & Expiry', 'Inventory', 'Age of stock and batches near / past expiry.', ['Choose buckets and near-expiry days.']),
    R('/reorder', 'Re-order & Over-stock', 'Inventory', 'Items below re-order level or above maximum.', ['Choose warehouse.']),
    R('/production-report', 'Production Reports', 'Inventory', 'Production register, raw material consumption, BOM vs actual, cost trend.', ['Choose the view and period.'], nature=['manufacturing', 'poultry']),
    R('/analytics', 'Forecasting & Inventory Analytics', 'Analysis', 'FSN, ABC, XYZ, ABC-XYZ, stock cover, turnover, dead stock, sales / purchase forecast, purchase plan, cash flow forecast, period comparison, customer RFM, expense comparison, DSO / DPO.',
      ['Choose the view from the menu and the period.']),

    # ================= DASHBOARDS / OFFICE / TOOLS =================
    R('/dashboard', 'Dashboard', 'Analysis', 'Customisable dashboard: sales, purchase, cash, receivables, stock and task widgets with charts.', ['Add / arrange widgets.']),
    R('/work-dashboard', 'Work Dashboard', 'Office', 'Tasks and darta / chalani at a glance.', ['Filter by your tasks / all.']),
    M('/help-center', 'Help Center', 'Tools', 'All manuals: complete user manual, one per business nature, IRD billing architecture and user manual; for super admin also the developer guide, the logic audit and the PDF of every menu screen.',
      ['Read in the browser or download the PDF.', 'Every screen also has ❓ Help on its toolbar (Shift+F1) and a tooltip on each field caption.']),
    R('/reports', 'Report Center', 'Tools', 'Every report in one place with search.', ['Search or open a group.']),
    M('/tasks', 'Tasks', 'Office', 'Tasks with assignee, due date, priority, status, comments and reminders.', ['New task; update status; filter overdue.']),
    M('/darta-chalani', 'Darta / Chalani', 'Office', 'Incoming (darta) and outgoing (chalani) letters register with numbers per fiscal year.', ['Add a darta / chalani; attach the scan; follow up pending.']),
    M('/mobile', 'Salesman Mobile App', 'Tools', 'Mobile screen for salesmen: the routes planned for them on the day, customers in visiting sequence, orders, cash receipts, sales returns, stock, visits.',
      ['Today: only the route(s) planned for this salesman on this date (a date-range plan shows on each date of the range). Open a route: its customers in sequence, with search.',
       'Per customer: Order, Receipt (cash / cheque / online), No order (reason), Details.',
       'Return tab: choose area and route (any), the customer, items and qty, reason - saved as a pending Sales Return.',
       'Entries tab: own orders, and receipts / returns with their approval state.'],
      other='Orders reach Sales Order with source "mobile". Receipts and returns are drafts tagged with the salesman as agent; the office posts them in Mobile Approvals. Settings per salesman in Route Plan > Mobile: allow receipts / returns, mobile cash ledger, off-route.'),

    # ================= POULTRY =================
    R('/poultry', 'Poultry Dashboard', 'Poultry', 'Running batches, mortality, FCR, livability, hatchery figures.', ['Open a batch or the hatchery.'], nature=['poultry']),
    M('/poultry/batches', 'Broiler Batches', 'Poultry',
      'Shed-wise broiler batches: placement (chicks), daily log (feed / medicine / vaccine used, mortality, culls, weight), lifting (birds sold), close; KPIs and profitability.',
      ['New Batch: shed, date, chicks placed (stock out of chick stock).', 'Daily log: consumption posts stock adjustments with the batch cost center.', 'Lifting: makes a draft Sales Bill.', 'Close the batch.'],
      nature=['poultry'], stock='Chicks, feed, medicine, vaccine go out through stock adjustments with the batch / shed cost center.',
      accounts='Through the normal documents (stock adjustments, sales bills, expenses with the batch cost center).',
      other='Livability, FCR, EPEF and profit per batch.'),
    M('/poultry/hatchery', 'Hatchery', 'Poultry', 'Egg setting, candling, hatch (A / B grade chicks), fertility, hatchability and chick cost; chicks can go to own sheds.',
      ['Set eggs, record candling and hatch results.'], nature=['poultry'], stock='Eggs out, chicks in through stock adjustments.'),
    R('/poultry/reports', 'Poultry Reports', 'Poultry', 'Shed / batch profitability, lifecycle, mortality, consumption.', ['Choose the view.'], nature=['poultry']),
    M('/poultry/setup', 'Poultry & Hatchery Setup', 'Poultry', 'Sheds / hatchers, poultry items (chick, feed, medicine ...), breed standards, ledgers and warehouse.', ['Fill each tab once.'], nature=['poultry']),

    # ================= CONSTRUCTION =================
    R('/construction', 'Construction Dashboard', 'Construction', 'Sites with contract value, billed, cost and profit.', ['Open a site.'], nature=['construction']),
    M('/construction/sites', 'Sites / Contracts', 'Construction',
      'Contract sites (own and petti thekka taken) with BOQ, running bills to the client, material issued, wages, sub-contracts given and other cost.',
      ['New site: client, contract value, cost center.', 'BOQ items.', 'RA (running) bill: work done, VAT, retention, TDS, advance recovery - posted to the GL.', 'Material: from store or straight from a purchase bill.', 'Wages sheets, sub-contract bills.'],
      nature=['construction'], accounts='RA bill: Dr client (and retention / TDS / advance) / Cr contract income / Cr VAT.',
      stock='Material issued to the site goes out of the store (consumption with the site cost center).', vat='RA bill VAT is output VAT.',
      other='Site profit = billed + other income - (material + wages + sub-contract + other cost).'),
    R('/construction/reports', 'Construction Reports', 'Construction', 'Site profit / loss, running bill register, petti thekka register, material consumed, wages.', ['Choose the view.'], nature=['construction']),
    M('/construction/setup', 'Construction Setup', 'Construction', 'Ledgers and settings of the construction module.', ['Set once.'], nature=['construction']),

    # ================= AUTOMOBILE =================
    R('/auto', 'Automobile Dashboard', 'Automobile', 'Enquiries, bookings, vehicles in stock, job cards, reminders.', ['Open a list.'], nature=['automobile']),
    M('/auto/enquiries', 'Customer Enquiries', 'Automobile', 'Showroom enquiries with follow-ups, test drive, booking, lost reason.', ['New enquiry; follow up; convert to booking / delivery.'], nature=['automobile']),
    M('/auto/vehicles', 'Vehicles / PDI / Delivery', 'Automobile', 'Vehicles in stock (by chassis), PDI checklist, delivery to the customer (documents, keys, accessories), free-service reminders.',
      ['PDI the vehicle.', 'Deliver: link the Sales Bill of the vehicle.'], nature=['automobile'],
      accounts='The vehicle sale is posted by its Sales Bill.', stock='The vehicle (serial = chassis) goes out with the Sales Bill.'),
    M('/auto/job-cards', 'Job Cards', 'Automobile', 'Workshop job cards: complaints, labour, parts issued from stock, outside work, ready / delivered, invoice.',
      ['New job card: vehicle, odometer, complaints.', 'Issue parts (stock out), add labour and outside work.', 'Ready -> Delivered: the job invoice posts.'], nature=['automobile'],
      accounts='Job invoice: Dr customer / Cr labour and parts income / Cr VAT.', stock='Parts go out through stock adjustments linked to the job.'),
    M('/auto/reminders', 'Service Reminders', 'Automobile', 'Due / overdue service reminders by date or km.', ['Follow up and mark done.'], nature=['automobile']),
    R('/auto/reports', 'Automobile Reports', 'Automobile', 'Enquiry analysis, vehicle delivery register, job card register, parts issued, outside work, technician performance.', ['Choose the view.'], nature=['automobile']),
    M('/auto/setup', 'Automobile Setup', 'Automobile', 'Models, free services, checklists, ledgers of the automobile module.', ['Set once.'], nature=['automobile']),
]
