# -*- coding: utf-8 -*-
"""Field help: what each caption on the forms does and where its effect goes.

Keys are the captions as they appear on the screens (without the * of a
compulsory field). The same text is shown
  * as the tooltip of that caption on every form (client/src/help/HelpTips),
  * in the Help panel of the page, and
  * in the menu PDFs and user manuals (docs/tools/build_help.py).
Aliases map other spellings of the same caption to one text.
"""

FIELDS = {
    # ---------- document header (all entries) ----------
    'Date': 'Date of the document. Accounts, stock, VAT month and ageing all use this date. Type it (AD or BS - switch with the AD/BS button) or pick it. A date in a closed fiscal year cannot be posted.',
    'Voucher No.': 'Number of the document. Given automatically on save from Document Numbering (series per fiscal year); shown as "System series" until then. Manual numbering only if the series allows it.',
    'Doc No': 'Number of the document. Given automatically on save from Document Numbering (series per fiscal year).',
    'Cash / Credit': 'Cash: paid / received now - the party field becomes a name (or a cash ledger) and no outstanding is created. Credit: the amount stays outstanding against the party (bill-wise, ageing, credit limit).',
    'Invoice Type': 'Cash or credit, as Cash / Credit: decides whether the document leaves an outstanding against the party.',
    'Customer': 'The customer (ledger in Sundry Debtors). Debited with the bill total (credited on a return). PAN, address, credit limit, rate category, agent and area come from the customer master.',
    'Vendor': 'The supplier (ledger in Sundry Creditors). Credited with the bill total (debited on a return / debit note). PAN, address and credit days come from the vendor master.',
    'Party': 'The customer / supplier ledger the document is with. Its balance moves with the document.',
    'Customer Sub-Ledger': 'Sub-ledger (e.g. branch or project of the customer) under the customer ledger. The party posting carries it, so sub-ledger statements and ageing show it.',
    'Vendor Sub-Ledger': 'Sub-ledger under the vendor ledger. The party posting carries it (sub-ledger statement / ageing).',
    'Quotation No.': 'Pull from a pending quotation of this party: its lines (pending qty only), master part (company, agent, sub-ledger ...), remarks and billing terms come into this entry. Enter on the box opens the list.',
    'Order No.': 'Pull from a pending order of this party (pending qty only). Master part, remarks and billing terms come along. The order\'s delivered / billed qty moves when this entry posts.',
    'Challan No.': 'Pull from a pending delivery challan. The stock already went out on the challan, so the bill lines from it do not move stock again.',
    'GRN No.': 'Pull from a pending GRN (goods received). Stock came in on the GRN; the bill clears the GRN clearing account and books the real payable.',
    'Bill No.': 'Pull from a posted bill of this party (for a return): only the qty not yet returned is offered.',
    'Rate Type': 'Which selling rate (Sr1 - Sr5) the lines use. Defaults from the customer\'s rate category; changing it re-rates the lines after asking.',
    'Product Company': 'Company / brand of the goods on this document. With "Product Company Compulsory" in System Control, only that company\'s products can be picked and the party posting is split by company (company-wise ledger / ageing).',
    'Warehouse': 'Warehouse the stock goes out of / comes into (only with Multi Warehouse on). A line can have its own warehouse.',
    'Master Warehouse': 'Default warehouse for all lines of this document.',
    'Salesman / Agent': 'Salesman / agent of the sale: used for agent-wise sales, targets and commission.',
    'Agent': 'Salesman / agent: agent-wise reports, targets and commission.',
    'Salesman/Agent': 'Salesman / agent: agent-wise reports, targets and commission.',
    'Area': 'Area of the party / sale - area-wise reports and data access.',
    'Route': 'Delivery / sales route - route-wise sales, loading sheet and route plan.',
    'Cost Center': 'Cost center (department, project, site, shed ...) every posting of this document carries: P&L by cost center, budgets.',
    'Unit': 'Business unit (division / brand) every posting carries: P&L by unit, budgets.',
    'Unit (Business Unit)': 'Business unit every posting carries: P&L by unit, budgets.',
    'Due Date': 'Payment due date (Date + credit days). Ageing, overdue interest and reminders use it.',
    'Due Days': 'Credit days; the due date is the document date plus these days.',
    'Currency': 'Currency of the document (Multi Currency on). Amounts are entered in it; the exchange rate converts them to NPR for accounts.',
    'Priority': 'Urgency of the document (normal / high / urgent) - for follow-up lists only.',
    'Narration': 'One line description printed on the voucher and shown in the ledger. Pick a saved remark or type.',
    'Remarks': 'Remarks printed on the document; pick a saved remark (Remarks master) or type your own.',
    'Terms & Conditions': 'Terms printed at the bottom of the document (Remarks & Terms master).',
    'Sales Account': 'Sales (income) account for this document when the product has none. Product account > this account > System Control Sales Account Mapping.',
    'Sales Sub-Ledger': 'Sub-ledger of the sales account for this document.',
    'Goods Account': 'Purchase / goods account for this document when the product has none. A fixed asset or stock ledger can be chosen for capital purchases.',
    'Goods Sub-Ledger': 'Sub-ledger of the goods account.',
    'Party Bill No': 'The supplier\'s own bill number (VAT invoice no). It goes to the purchase VAT register; the same number cannot be entered twice for one supplier.',
    'Party Bill Date': 'Date on the supplier\'s bill - VAT register and Annex 13.',
    'Return Reason': 'Why the goods came back: printed on the credit note, sent to IRD for sales returns.',
    'Settlement Type': 'How the return is settled: against the bill (adjusts that bill\'s outstanding) or on account.',
    'Terms': 'Billing terms (VAT, excise, discount, freight ...) of the document.',
    'Import Declaration No': 'Customs declaration (pragyapan patra) number of an import - VAT register import columns.',
    'Declaration Date': 'Date of the customs declaration.',
    'Customs Office (Bhansar)': 'Customs office of the import.',
    'Import Detail Mode': 'Import taxable / tax-free amounts for the whole bill, or item-wise.',
    'Import Taxable Amount (whole bill)': 'Taxable import value for the VAT register (Annex).',
    'Import Tax-Free Amount (whole bill)': 'Tax-free import value for the VAT register.',
    'PAN Number': 'PAN / VAT number of the party printed on the bill and used in VAT registers / IRD. Can update the master.',
    'Link to Order': 'Order whose lines this additional expense is allocated to (landed cost).',
    'Link to GRN': 'GRN whose lines this additional expense is allocated to (landed cost goes into the stock value).',
    'Link to Bill': 'Purchase bill whose lines this additional expense is allocated to (landed cost).',
    'Account Posting': 'Yes: the expense is posted to the ledgers. No: only the landed cost moves (e.g. already booked elsewhere).',

    # ---------- line grid ----------
    'Item Code': 'Product code or barcode - type or scan; Enter moves on. F1 shows this customer\'s / supplier\'s rate history.',
    'Item Name': 'The product. Its units, rates, accounts, VAT, batch / serial and item type come from the Product Master.',
    'Qty': 'Quantity in the selected unit. Stock moves in the product\'s base unit (converted automatically).',
    'Free Qty': 'Free (scheme) quantity: moves stock, no value.',
    'UOM': 'Unit of the line (box, pcs, kg ...). Conversion to the base unit comes from Product Units / the product.',
    'Alt Qty': 'Quantity in the second unit of a dual-unit product (e.g. pcs with cartons).',
    'Rate': 'Rate per unit (per the rate basis). Sales: from the rate type / rate category / offer rate; purchase: last purchase rate.',
    'Rate Basis': 'Whether the rate is per the primary or the secondary unit of a dual-unit product.',
    'Gross': 'Qty x rate before discounts and terms.',
    'Add / Less': 'Product-wise charges and discounts of the line (from its billing terms popup when Item Charges is on); the popup total shows here.',
    'Net Amount': 'Gross +/- the line terms: the value of the line.',
    'Disc %': 'Line discount percent (a Discount billing term when term mapping is used).',
    'Tax %': 'VAT percent of the line (13% for taxable goods, 0 for exempt).',
    'Batch': 'Batch / lot number (Batch System on). Stock and batch-wise costing follow it.',
    'Serial No': 'Serial number of the piece (Serial Number on) - vehicles, electronics.',
    'Mfg Date': 'Manufacturing date of the batch.',
    'Exp Date': 'Expiry date of the batch - near-expiry alerts and stock ageing.',
    'Barcode': 'Barcode of the product / batch.',
    'Ref No (source doc)': 'The document this line was pulled from (quotation / order / challan / GRN / bill).',

    # ---------- footer / totals ----------
    'Gross Amount': 'Total of the lines before document-level terms.',
    'Net Amount (total)': 'Amount after all terms and VAT - the party is debited / credited with it.',

    # ---------- receipt / TDS on bills ----------
    'Base': 'Amount TDS is worked out on (default: the bill value without VAT).',
    'TDS %': 'TDS rate. TDS amount = base x %. Sales: TDS the customer withholds (Dr TDS receivable, Cr customer). Purchase: TDS we withhold (Dr supplier, Cr TDS payable).',
    'TDS Amount': 'TDS in rupees; typed or worked out from base x %.',
    'TDS Ledger': 'TDS payable (purchase) or TDS receivable (sales) ledger; defaults from System Control.',
    'TDS Sub-Ledger': 'Sub-ledger of the TDS ledger (e.g. TDS type / section).',

    # ---------- journal voucher ----------
    'JV Type': 'Kind of journal: Normal, Taxable / non-taxable Purchase or Sales, Asset Purchase / Sale, Service Purchase / Sale, or TDS (on purchase / on sales). Purchase / sales types go to the VAT register; the lines are filled from the amounts.',
    'Taxable Amount': 'Value on which VAT is charged (JV purchase / sales).',
    'Non-taxable Amount': 'VAT-exempt value (JV purchase / sales).',
    'VAT %': 'VAT rate (13%); VAT amount = taxable x %.',
    'VAT Amount': 'VAT of the journal - posted to the VAT A/c and to the VAT register.',
    'VAT A/c': 'VAT ledger the VAT goes to (defaults from System Control).',
    'Bill Total': 'Taxable + non-taxable + VAT: the party amount.',
    'Ref Doc No': 'Reference document (supplier bill no for a purchase).',
    'Ref Doc Date': 'Date of the reference document.',
    'Bill Date': 'Date of the supplier / customer bill.',
    'PAN / VAT No': 'PAN of the party (VAT register).',
    'Memo Only': 'A memo journal is recorded but not posted to the ledgers.',

    # ---------- cash / bank ----------
    'Receipt / Payment': 'Receipt: money comes in (Dr cash / bank, Cr the lines). Payment: money goes out (Cr cash / bank, Dr the lines).',
    'Cash / Bank': 'Whether the cash or a bank account is used.',
    'Cash/Bank Ledger': 'The cash-in-hand or bank ledger debited (receipt) or credited (payment).',
    'Mode': 'Cash, cheque, transfer, wallet ... printed and used by bank reconciliation.',
    'Cheque / Txn No': 'Cheque or transaction number - bank reconciliation matches it with the statement.',
    'Document No': 'Reference number (receipt book no, bank slip no).',
    'Document Date': 'Date of the reference document / cheque.',

    # ---------- PDC ----------
    'Received / Issued': 'Received: a post-dated cheque from a customer. Issued: our post-dated cheque to a supplier. Nothing posts to the ledger until the cheque is deposited / cleared.',
    'Cheque No': 'Number of the post-dated cheque.',
    'Cheque Date': 'Date on the cheque; the PDC dashboard shows due / overdue cheques by it.',
    'Bank Ledger': 'Bank the cheque is deposited to / paid from when it clears.',
    'Bank Name': 'Bank of the cheque.',
    'Amount': 'Amount of the line / cheque / document.',

    # ---------- stock transfer / production ----------
    'From Warehouse': 'Warehouse the goods leave (stock out).',
    'To Warehouse': 'Warehouse the goods reach (stock in).',
    'From Branch': 'Sending branch (branch transfer: goods in transit until received).',
    'To Branch': 'Receiving branch.',
    'Transfer Type': 'Direct (in and out together) or two-step branch transfer (dispatch, then receipt).',
    'Receiving Date': 'Date the goods were received at the other branch.',
    'Vehicle No': 'Vehicle carrying the goods - printed on the challan / transfer.',
    'Driver Name': 'Driver of the vehicle.',
    'Transport': 'Transporter (Transport Master).',
    'Output Product': 'Finished / semi-finished product made. Stock in at the cost of the raw materials (less by-products) per base unit.',
    'Output Qty': 'Quantity produced.',
    'Output Warehouse': 'Warehouse the output goes into.',
    'Source Warehouse (Raw Material)': 'Warehouse the raw materials are taken from.',
    'Output Batch No': 'Batch number of the production.',
    'Output Relative Value': 'Share of cost for the main output when there are joint products (relative sales value).',

    # ---------- masters ----------
    'Account Name': 'Name of the ledger.',
    'Account Group': 'Group the ledger belongs to - decides Balance Sheet / P&L place, Trial Balance and ratio / cash-flow category.',
    'Category Type': 'Customer, supplier, both, cash, bank or others - decides where the ledger is offered (party pickers, cash / bank).',
    'Opening Balance': 'Balance on the first day of the opening fiscal year (Dr / Cr).',
    'Credit Limit / Days': 'Maximum outstanding and credit days allowed - warned / blocked on sales per Credit Limit Control.',
    'Credit Limit Control': 'None, warn or block when a sale takes the party over its credit limit.',
    'Bill-wise Tracking': 'Keep the party\'s outstanding bill by bill (bill-wise ageing, settlement of payments against bills).',
    'Sub Ledger Mode': 'Whether this ledger uses sub-ledgers and which.',
    'VAT/PAN Number': 'PAN / VAT number - printed on bills, VAT register, IRD, confirmation letters.',
    'Billing Name': 'Name printed on bills (if different from the ledger name); confirmation letters can group ledgers by it.',
    'Rate Category': 'Which selling rate (Sr1 - Sr5) this customer gets by default.',
    'Discount Category': 'Default discount group of the customer.',
    'Interest % p.a.': 'Interest on overdue bills (Interest on Overdue posting).',
    'Product Name': 'Name of the product.',
    'Item Type': 'Trading item, raw material, semi-finished, finished good, service, non-inventory or fixed asset. Service, non-inventory and fixed asset are not stock (no stock movement, not in closing stock).',
    'Primary Unit': 'Base unit of the product: stock is kept in it.',
    'Unit Mode': 'Single unit, multiple units with conversion, or dual unit (two quantities per line).',
    'HS Code': 'Harmonised System code (customs / VAT annex).',
    'Stock Group': 'Product group - group-wise stock and sales reports.',
    'Company / Brand': 'Product company - company-wise sales, purchase and compulsory company rules.',
    'Default Vendor': 'Usual supplier - used by purchase plans.',
    'Short Name': 'Short name / alias for quick search.',
    'Short Name (Alias)': 'Short name / alias for quick search.',
    'Code': 'Code of the record - automatic and read-only.',
    'Tags': 'Free labels for searching and grouping.',

    # ---------- reports ----------
    'From': 'First date of the report period.',
    'To': 'Last date of the report period.',
    'From Date': 'First date of the report period.',
    'To Date': 'Last date of the report period.',
    'As on': 'Report position at the end of this date (balances, stock, ageing).',
    'Show': 'Which rows to show (all / only differences / ...).',
    'Group by': 'How the rows are grouped / totalled.',
    'View': 'Layout of the report.',
    'Side': 'Sales side or purchase side.',
    'Documents': 'Which document types are included. The book buttons tick a whole book at once (bills + JVs + additional bills).',
    'Customer / Supplier': 'Limit the report to one party.',
    'Status': 'Document status: draft, posted, cancelled ...',
    'Method': 'Stock valuation method: FIFO, moving average, weighted average ...',
    'Search': 'Find rows containing this text.',

    # ---------- system control (selection) ----------
    'IRD Billing': 'Yes: a posted Sales Bill / Sales Return can only be cancelled (IRD rules), is kept in the IRD register and can be pushed to CBMS.',
    'VAT Ledger Mapping': 'Default VAT ledger for line VAT on sales and purchase.',
    'Negative Stock Control': 'None / warn / block when a sale, return, transfer or adjustment would take stock below zero.',
    'Multi Warehouse': 'Yes: warehouse on entries and warehouse-wise stock.',
    'Batch System': 'Yes: batch / lot on stock entries and batch-wise stock.',
    'Multi Currency System': 'Yes: foreign-currency documents with exchange rates.',
    'Default VAT %': 'VAT rate used when a line has none (13%).',
    'Default TDS %': 'TDS rate offered on bills / JVs.',
    'TDS Payable Ledger (purchase)': 'Ledger for TDS we withhold from suppliers.',
    'TDS Receivable Ledger (sales)': 'Ledger for TDS customers withhold from us.',
    'Sales Account Mapping': 'Default sales account (when neither product nor document has one).',
    'Purchase Account Mapping': 'Default purchase account.',
    'GRN Clearing Ledger (GR/IR)': 'Provisional liability for goods received before the bill (Cr at GRN, Dr at bill).',
    'Post Stock Adjustment to Accounts': 'Yes: stock adjustments post to the ledgers (shortage / damage / excess accounts).',
    'Back-date Entry Control': 'How far back an entry may be dated.',
    'Post-date Entry Control': 'How far ahead an entry may be dated.',
}

ALIASES = {
    'Salesman': 'Salesman / Agent',
    'Customer Sub Ledger': 'Customer Sub-Ledger',
    'Party Sub Ledger': 'Customer Sub-Ledger',
    'Date From': 'From',
    'Date To': 'To',
    'Terms &amp; Conditions': 'Terms & Conditions',
    'Doc No.': 'Doc No',
    'Posting date': 'Date',
    'VAT/PAN Type': 'VAT/PAN Number',
    'Serial': 'Serial No',
    'Free': 'Free Qty',
    'Net Amt': 'Net Amount',
    'Disc': 'Disc %',
}
