# -*- coding: utf-8 -*-
"""Page help - data entry screens (sales, purchase, accounts, inventory,
production). Each entry: purpose, steps, effect on accounts / stock / VAT and
other modules, tips. Field captions of the screen are added by build_help.py
from the page source and explained from help_fields.py."""

ALL = ['trading', 'distribution', 'retail', 'manufacturing', 'service', 'automobile', 'construction', 'poultry']

COMMON_SALES = [
    'Choose the date (AD / BS), Cash or Credit, then the customer. Quotation / Order / Challan No. boxes right after the customer pull pending documents of that customer (Enter opens the list).',
    'Add lines: item code or barcode, qty, unit, rate (from the customer\'s rate type), discount; Add / Less opens the product-wise terms when Item Charges is on.',
    'Check the footer: gross, terms (VAT, discount, freight), net amount; party address / PAN tab can update the master.',
    'Save (or Save as Draft). The action bar also has New, Modify, Cancel, Remove and Print.',
]
COMMON_PURCHASE = [
    'Choose the date, Cash or Credit, then the vendor. Quotation / Order / GRN No. boxes right after the vendor pull pending documents (Enter opens the list).',
    'Add lines: item, qty, unit, rate, discount; product-wise terms through Add / Less; document terms (VAT, freight) in the footer.',
    'Save (or Save as Draft). New, Modify, Cancel, Remove and Print are on the action bar.',
]

PAGES = [
    # ================= SALES =================
    dict(path='/sales-quotation', title='Sales Quotation', module='Sales', kind='entry', nature=ALL,
         purpose='Price offer to a customer. Pending quotation lines can be pulled into a Sales Order, Challan or Bill.',
         steps=COMMON_SALES,
         accounts='None - a quotation posts nothing.', stock='None.', vat='None.',
         other='Its qty is "pending" until pulled forward; the Order / Challan / Bill made from it reduces the pending qty.',
         tips=['Use Copy on a posted quotation to make a similar one.', 'Quotation Register (Universal Register) lists them with status.']),
    dict(path='/sales-order', title='Sales Order', module='Sales', kind='entry', nature=ALL,
         purpose='Customer\'s confirmed order. Checks the credit limit; can be billed later (single or many orders at once in Order -> Bill).',
         steps=COMMON_SALES + ['Pull from a quotation with Quotation No. if one was given.'],
         accounts='None.', stock='None (only reserved in order reports).', vat='None.',
         other='Pending order qty feeds Pending Orders, Order Fill Rate and the salesman order register. Credit limit control warns / blocks per the customer.'),
    dict(path='/order-billing', title='Order -> Bill (single / multiple)', module='Sales', kind='entry', nature=ALL,
         purpose='Turn one or many pending sales orders into sales bills in one go, with qty / rate changes.',
         steps=['Filter orders (date, customer, agent, route).', 'Tick the orders; adjust qty / rate per line.', 'Make bills: one bill per customer.'],
         accounts='Each bill made posts like a Sales Bill.', stock='Stock goes out with each bill.', vat='Output VAT on each bill.',
         other='The orders\' billed qty moves; fully billed orders close.'),
    dict(path='/sales-delivery', title='Sales Delivery / Challan', module='Sales', kind='entry', nature=ALL,
         purpose='Goods sent to the customer before the bill (delivery note / challan).',
         steps=COMMON_SALES + ['Vehicle, driver and transport can be recorded for the challan print.'],
         accounts='None - the bill made from it posts the sale.', stock='Stock goes OUT on posting (warehouse / batch / serial of each line). Negative Stock control applies.',
         vat='None (VAT is on the bill).', other='Challan No. on the Sales Bill pulls it; those bill lines do not move stock again.'),
    dict(path='/sales-bill', title='Sales Bill / Invoice', module='Sales', kind='entry', nature=ALL,
         purpose='Tax invoice to the customer. Posts the sale, the VAT and (for a direct bill) takes the stock out.',
         steps=COMMON_SALES + [
             'Receipt / TDS tab: record money received now - cash and / or several banks, one line each - (cash bill: all of it; credit bill: part payment allowed) and TDS the customer withholds.',
             'With IRD Billing on, a posted bill cannot be modified or removed - only cancelled.'],
         accounts='Dr Customer (bill total) / Cr Sales account per line (product account > document Sales Account > System Control) / Cr VAT ledger / terms to their ledgers. Receipt lines: Dr cash / bank, Cr customer. TDS: Dr TDS receivable, Cr customer.',
         stock='Direct lines (not from a challan) go OUT of stock. Services, non-inventory and fixed-asset lines do not move stock. Negative Stock control applies (confirm to post anyway when allowed).',
         vat='Output VAT to the Sales VAT register, VAT return, IRD register and CBMS.',
         other='Order / challan pending qty moves; bill-wise outstanding (credit); agent sales and commission; customer credit limit; IRD print count.',
         tips=['F1 on a line shows this customer\'s rate history for the item.', 'Cancel reverses accounts, stock and IRD status; a posted bill is never deleted under IRD.']),
    dict(path='/sales-return', title='Sales Return', module='Sales', kind='entry', nature=ALL,
         purpose='Goods coming back from a customer (credit note), normally against a bill.',
         steps=['Choose the customer and pull the bill with Bill No. - only the qty not yet returned is offered.', 'Give the return reason and settlement type; adjust qty.', 'Save.'],
         accounts='Dr Sales Return account (product return account > sales account) / Dr VAT / Cr Customer.',
         stock='Goods come back IN at their cost (the cost that batch / serial went out at, else the current average) - never at the selling rate.',
         vat='Reduces output VAT (credit note in the VAT register; sent to CBMS as a bill return).',
         other='The bill\'s returned qty moves; bill-wise settlement against the bill.'),
    dict(path='/sales-nonsaleable-return', title='Sales Non-saleable Return', module='Sales', kind='entry', nature=ALL,
         purpose='Damaged / expired goods returned by a customer that cannot be sold again.',
         steps=['Pull the bill with Bill No., enter the damaged qty and reason.', 'Save.'],
         accounts='Dr Non-saleable return account / Cr customer.', stock='Kept apart as non-saleable stock (not in saleable stock).',
         vat='As per the return.', other='Counts against the bill\'s returned qty together with normal returns.'),
    dict(path='/sales-additional-entry', title='Sales Additional Entry', module='Sales', kind='entry', nature=ALL,
         purpose='Extra charges or discounts on already issued sales bills (freight recovered, rate difference, scheme).',
         steps=['Choose the customer and the bill(s).', 'Add the charge / discount lines with their ledgers.', 'Save.'],
         accounts='Dr / Cr the customer against the chosen ledgers.', stock='None.', vat='As per the lines.', other='Bill-wise outstanding of the bill changes.'),
    dict(path='/agent-targets', title='Salesman Targets & Commission', module='Sales', kind='entry', nature=ALL,
         purpose='Targets per salesman (month / quarter / year, all products or a product / group / company / category, qty and / or value) and commission rules; achievement and commission posting.',
         steps=['Set Targets tab: add targets.', 'Target Achievement tab (the target report): target vs actual net sales, balance, achievement %; tick and post the earned commission (once per target).',
                'Bill-wise Commission tab: posted bills of the salesman (value without VAT, less returns against the bill) with the salesman\'s commission %; change the % or amount per bill, tick one or all and post. A bill that already got commission moves to "Commission already given" and is never offered again; cancelling the posting frees its bills.'],
         accounts='Commission posting: Dr commission expense / Cr salesman commission payable (ledgers from the salesman master, or chosen on posting).', stock='None.', vat='None.',
         other='Commission Register lists every posting (target-wise and bill-wise) and cancels it (the GL entry is reversed).'),
    dict(path='/mobile-approvals', title='Mobile Approvals (receipts / returns)', module='Sales', kind='entry', nature=ALL,
         purpose='Cash receipts and sales returns the salesmen entered on the phone wait here as pending drafts until the office posts them.',
         steps=['Filter by type, status, salesman and dates.', 'Tick one, several or all (tick box in the header) and Post ticked.', 'Open screen opens Cash / Bank Entry or Sales Return to change an entry before posting.'],
         accounts='On posting - receipt: Dr the mobile cash ledger, Cr the customer (bill-wise settled); return: as Sales Return. The salesman is the agent on both.',
         stock='Return: goods come back in on posting.', vat='Return: reduces output VAT on posting.',
         other='Pending entries have no effect at all. The salesman sees them as "Pending approval" on the phone.'),

    # ================= PURCHASE =================
    dict(path='/purchase-quotation', title='Purchase Quotation', module='Purchase', kind='entry', nature=ALL,
         purpose='Supplier\'s price offer; can be pulled into a Purchase Order, GRN or Bill.',
         steps=COMMON_PURCHASE, accounts='None.', stock='None.', vat='None.', other='Pending qty until pulled forward.'),
    dict(path='/purchase-order', title='Purchase Order', module='Purchase', kind='entry', nature=ALL,
         purpose='Order placed on a supplier; received later with a GRN or a direct bill.',
         steps=COMMON_PURCHASE, accounts='None.', stock='None.', vat='None.',
         other='Pending order qty; additional expenses (freight, duty) can be linked to the order and reach the goods when received.'),
    dict(path='/purchase-grn', title='Purchase GRN (Goods Received)', module='Purchase', kind='entry', nature=ALL,
         purpose='Goods received before the supplier\'s bill.',
         steps=COMMON_PURCHASE + ['Enter the supplier\'s challan no / date.'],
         accounts='Dr goods (purchase) account / Cr GRN Clearing (GR/IR) ledger - a provisional liability until the bill comes.',
         stock='Stock comes IN at the goods value without VAT per base unit (after discount and non-VAT terms), plus landed cost of additional expenses posted against it.',
         vat='None yet (VAT is taken on the bill).', other='GRN Outstanding lists GRNs not yet billed; the Purchase Bill pulls it with GRN No.'),
    dict(path='/purchase-bill', title='Purchase Bill', module='Purchase', kind='entry', nature=ALL,
         purpose='Supplier\'s tax invoice. Books the purchase, input VAT and the payable.',
         steps=COMMON_PURCHASE + ['Party Bill No / Date: the supplier\'s invoice number (cannot be entered twice for the same supplier).', 'TDS tab: TDS withheld from the supplier.', 'Import fields for imports (declaration no, customs office, taxable / tax-free import value).'],
         accounts='Direct bill: Dr goods account per line / Dr VAT / Cr vendor. Bill from a GRN: Dr GRN Clearing / Cr vendor, VAT moved out of the goods account. TDS: Dr vendor / Cr TDS payable.',
         stock='Direct lines come IN at the goods value without VAT per base unit; lines from a GRN do not move stock again. Services / fixed assets do not go to stock.',
         vat='Input VAT to the Purchase VAT register and VAT return (claimable).',
         other='Order / GRN pending qty; bill-wise payable; TDS register; Purchase vs Stock reconciliation.'),
    dict(path='/purchase-bill-import', title='Purchase Bill from Image / PDF', module='Purchase', kind='entry', nature=ALL,
         purpose='Read a supplier bill photo / PDF (OCR) into a purchase bill draft.',
         steps=['Upload the image / PDF.', 'Check the read supplier, bill no, lines and amounts; map items.', 'Create the draft bill and post it from Purchase Bill.'],
         accounts='Only when the bill is posted.', stock='Only when posted.', vat='Only when posted.'),
    dict(path='/purchase-additional-expense', title='Purchase Additional Expense', module='Purchase', kind='entry', nature=ALL,
         purpose='Freight, customs, clearing, insurance, labour ... on purchased goods - taxable or non-taxable bills of other parties, or no bill - allocated to the goods (landed cost).',
         steps=['Link to the Order, GRN and / or Bill the cost belongs to - the vendor of that document comes in as the vendor (change it when another party is paid).',
                'Product-wise Terms tab: the products of the linked document; Terms… on a product opens its terms (Billing Terms marked Purchase Additional + Product Wise) - rate % of that product\'s value or amount; the whole amount goes to that product\'s cost.',
                'Bill-wise Terms tab: a fixed form with one row per bill-level term - fill the amounts that apply; each is divided over the products by the term\'s basis (value / qty, changeable per row). Empty rows are left out.',
                'A term\'s ledger is fixed by the term - only its sub-ledger can be changed. "Paid to" (the counter ledger) and its sub-ledger are free; empty = the entry\'s vendor. Bill type (taxable / non-taxable / no bill), bill no and VAT per row; Add TDS Line for withholding.',
                'Check the per-product preview (additional, cost / unit), then Save and post.'],
         accounts='Dr each term / expense ledger with its sub-ledger (Cr for "-" terms) / Dr VAT (claimable) / Cr the party of each line with its sub-ledger. TDS lines: Cr TDS payable.',
         stock='Posted: the allocated amount is added to the cost of the stock receipt of each linked line (landed cost); cancelled: taken out again. Terms not "Include In Costing" stay out of the stock cost.',
         vat='Taxable lines go to the Purchase VAT register as "Purchase Additional Bill".',
         other='Purchase Account and Purchase vs Stock reconciliation show it separately; TDS register; bills can later be taken in a TDS journal.'),
    dict(path='/purchase-return', title='Purchase Return', module='Purchase', kind='entry', nature=ALL,
         purpose='Goods sent back to the supplier (debit note), normally against a bill.',
         steps=['Choose the vendor, pull the bill with Bill No.', 'Adjust qty, give Party Bill No (credit note ref).', 'Save.'],
         accounts='Dr vendor / Cr purchase return account / Cr VAT.',
         stock='Goods go OUT (Negative Stock control applies).', vat='Reduces input VAT.', other='The bill\'s returned qty moves.'),
    dict(path='/purchase-nonsaleable-return', title='Purchase Non-saleable Return', module='Purchase', kind='entry', nature=ALL,
         purpose='Damaged / expired stock sent back to the supplier.',
         steps=['Pull the bill with Bill No.', 'Enter qty and reason.', 'Save.'],
         accounts='Dr vendor / Cr non-saleable return account.', stock='Out of non-saleable stock.', vat='As per the return.'),
    dict(path='/lc-register', title='LC Register & Mapping', module='Purchase', kind='entry', nature=ALL,
         purpose='Letters of credit for imports: amount, bank, expiry, and which purchase documents used them.',
         steps=['Add the LC.', 'Map purchase orders / bills to it.', 'Actions: amend, close, extend.'],
         accounts='None by itself (margin / charges through Cash / Bank or JV).', stock='None.', vat='None.',
         other='LC / BG / PDC dashboard warns on expiry and over-use.'),

    # ================= ACCOUNTS =================
    dict(path='/journal-voucher', title='Journal Voucher', module='Accounts', kind='entry', nature=ALL,
         purpose='Any accounting entry, and typed entries: taxable / non-taxable purchase or sales, asset purchase / sale, service purchase / sale, TDS on purchase / sales.',
         steps=['Choose the JV Type.', 'Purchase / sales types: party, bill no / date, taxable, non-taxable, VAT % - the lines (e.g. Purchase 2000 Dr, VAT 130 Dr, party 2130 Cr) are filled and can be changed.',
                'TDS types: choose the party, tick its bills (newest first), give TDS % per bill - lines are made; a bill used once is not offered again.',
                'Normal: enter Dr / Cr lines; picking a ledger on the next line puts the balancing amount.', 'One narration; Save.'],
         accounts='Exactly the lines (Dr = Cr, enforced by the database).', stock='None.',
         vat='Purchase / sales / asset / service types go to the VAT register (JV Purchase / JV Sales).',
         other='TDS types: TDS register and the record of bills already taken.'),
    dict(path='/cash-bank-entry', title='Cash / Bank Entry', module='Accounts', kind='entry', nature=ALL,
         purpose='Receipts and payments through cash or bank.',
         steps=['Receipt or Payment; cash or bank ledger; mode, cheque / txn no.', 'Lines: the party / ledger, amount, bill-wise settlement for parties.', 'One narration; Save.'],
         accounts='Receipt: Dr cash / bank / Cr lines. Payment: Dr lines / Cr cash / bank.', stock='None.', vat='None.',
         other='Bill-wise settlement of the party\'s bills; bank reconciliation; cash negative balance control.'),
    dict(path='/debit-note', title='Debit Note', module='Accounts', kind='entry', nature=ALL,
         purpose='Supplier-side adjustment without goods (rate difference, claim, discount received).',
         steps=['Party, lines with ledgers and amounts (VAT line if any).', 'Save.'],
         accounts='Dr supplier / Cr the lines.', stock='None.', vat='Lines to a VAT ledger reduce input VAT (Debit Note in the VAT register).',
         other='Lines to a purchase account appear in the Purchase Account reconciliation.'),
    dict(path='/credit-note', title='Credit Note', module='Accounts', kind='entry', nature=ALL,
         purpose='Customer-side adjustment without goods (discount allowed, rate difference).',
         steps=['Party, lines with ledgers and amounts.', 'Save.'],
         accounts='Dr the lines / Cr customer.', stock='None.', vat='Lines to a VAT ledger reduce output VAT (Credit Note in the VAT register).',
         other='Lines to a sales account appear in the Sales Account reconciliation.'),
    dict(path='/pdc-voucher', title='PDC (Post-dated Cheque)', module='Accounts', kind='entry', nature=ALL,
         purpose='Post-dated cheques received from customers or issued to suppliers.',
         steps=['Received / Issued, party, cheque no, cheque date, bank, amount.', 'On the cheque date: deposit / clear, bounce or return from the PDC dashboard.'],
         accounts='Nothing until cleared; clearing posts a receipt / payment (bank Dr / Cr).', stock='None.', vat='None.',
         other='Ledger Summary / Party Summary can show PDC separately; the PDC dashboard lists due cheques.'),
    dict(path='/bulk-cash-settlement', title='Bulk Cash Settlement', module='Accounts', kind='entry', nature=ALL,
         purpose='Settle many cash-bill or party receipts at once (e.g. a salesman\'s day collection).',
         steps=['Choose parties / bills, amounts received.', 'Post.'], accounts='Receipts: Dr cash / Cr each party.', stock='None.', vat='None.',
         other='Bill-wise settlement of each bill.'),
    dict(path='/bank-reconciliation', title='Bank Reconciliation', module='Accounts', kind='entry', nature=ALL,
         purpose='Match the bank ledger with the bank statement (manual or by importing the statement).',
         steps=['Choose the bank ledger and period.', 'Import the statement (Excel / CSV) - auto-match by amount / cheque / date; confirm or match by hand.', 'BRS tab: balance per books, uncleared items, balance per bank.'],
         accounts='No posting (clearing dates only). Bank charges / interest found here are entered through Cash / Bank or JV.', stock='None.', vat='None.'),
    dict(path='/interest-posting', title='Interest on Overdue', module='Accounts', kind='entry', nature=ALL,
         purpose='Interest on customers\' overdue bills from the due date at the ledger\'s interest % p.a.',
         steps=['Choose the date and parties; check the calculated interest.', 'Post: a register row per party (posted once).'],
         accounts='Dr customer / Cr interest income.', stock='None.', vat='None.'),
    dict(path='/fixed-assets', title='Fixed Assets & Depreciation', module='Accounts', kind='entry', nature=ALL,
         purpose='Fixed asset register, depreciation (SLM / WDV by block), asset sale / value reduction; schedule and detail reports.',
         steps=['Assets tab: add assets (cost, date, block / rate, ledger).', 'Depreciation tab: calculate for the period and post.', 'Sale / value reduce from the asset row.'],
         accounts='Depreciation: Dr depreciation expense / Cr accumulated depreciation (or the asset). Sale: asset out, gain / loss.', stock='None.', vat='Asset purchase / sale VAT through the bill or JV.'),
    dict(path='/budgets', title='Budgets', module='Accounts', kind='entry', nature=ALL,
         purpose='Budgets by ledger, sub-ledger, cost center, unit or doc class and period; variance against actual.',
         steps=['Add budget lines per period.', 'Budget vs Actual shows actual, variance and %.'], accounts='None.', stock='None.', vat='None.'),
    dict(path='/confirmation-letters', title='Account Confirmation Letters', module='Accounts', kind='report', nature=ALL,
         purpose='Balance confirmation letters for customers / suppliers - one per ledger, per billing name or per PAN - with statement, open bills, purchases / sales by nature (Inventory, Fixed Asset, Service) and a reply slip.',
         steps=['Choose party type, group by, as-on date (and from date for a statement).', 'Pick a format (English, Nepali, with reply slip) or design your own.', 'Tick the parties and print.'],
         accounts='None (read only).', stock='None.', vat='Shows VAT on purchases / sales with the party.'),

    # ================= INVENTORY / PRODUCTION =================
    dict(path='/stock-transfer', title='Stock Transfer', module='Inventory', kind='entry', nature=ALL,
         purpose='Move stock between warehouses or branches (direct, or two-step dispatch and receipt).',
         steps=['From / to warehouse (branch), transfer type.', 'Lines: item, qty, batch.', 'Two-step: post the dispatch; the other branch receives it on its date.'],
         accounts='Only with "Post Stock Transfer to Accounts" on (branch stock ledgers / goods in transit).',
         stock='Out of the sending warehouse, into the receiving one (company stock unchanged). Dispatched but not received = goods in transit.', vat='None.'),
    dict(path='/barcode-print', title='Barcode / Label Printing', module='Inventory', kind='tool', nature=ALL,
         purpose='Print barcode labels for products / batches from purchases or a list.',
         steps=['Pick items (or a GRN / bill) and label count.', 'Choose a label format (designer) and print.'], accounts='None.', stock='None.', vat='None.'),
    dict(path='/production-order', title='Production Order', module='Production', kind='entry', nature=['manufacturing', 'poultry'],
         purpose='Make a product from raw materials (from a BOM template or by hand), with by-products.',
         steps=['Output product, qty, unit, warehouse; BOM template fills the raw materials.', 'Adjust raw material qty; add by-products (value).', 'Post.'],
         accounts='With WIP / production ledgers set: raw material consumption and output value.',
         stock='Raw materials OUT of the source warehouse; output IN at (raw material cost - by-product value) per base unit; by-products IN at their value.',
         vat='None.', other='Production register, consumption, BOM vs actual and cost trend reports.'),
    dict(path='/bom-template', title='BOM Template', module='Production', kind='master', nature=['manufacturing', 'poultry'],
         purpose='Bill of materials: raw materials (and by-products) for a given output qty.',
         steps=['Output product and qty.', 'Raw material lines with qty and unit.', 'Save; Production Order uses it.'], accounts='None.', stock='None.', vat='None.'),
]
