// =============================================
// utils/masterCodes.js
// Master codes: generated by the system, shown read-only on the create
// form before saving, never typed by the user.
//   format  = <fiscal year><separator><TYPE><running number>
//   ledger  = 8182LDG000001        (FY 2081/82, LDG, 6 digits)
//   product = 8182-PRD0000001      (FY 2081/82, "-", PRD, 7 digits)
// Every master has its own TYPE / separator / digits (System Control >
// Master Codes, stored in system_control_settings.master_code_format) and
// its own counter per fiscal year (master_code_counters, advanced
// atomically by tenant_master.next_master_no - migration 126).
// preview() only reads the counter, so opening a form uses no number.
// Short names: initials of the name + a running number (TPA00001),
// suggested on the form and freely changeable.
// =============================================

const MASTERS = {
    ledger: { label: 'General Ledger', table: 'ledger_accounts', col: 'account_code', prefix: 'LDG', sep: '', digits: 6, shortName: 'short_name', nameCol: 'account_name' },
    // ledgers are numbered by their type (the ledger's / its group's category)
    ledger_customer: { label: 'Customer Ledger', table: 'ledger_accounts', col: 'account_code', prefix: 'CUS', sep: '', digits: 6, shortName: 'short_name', nameCol: 'account_name' },
    ledger_supplier: { label: 'Supplier Ledger', table: 'ledger_accounts', col: 'account_code', prefix: 'SUP', sep: '', digits: 6, shortName: 'short_name', nameCol: 'account_name' },
    ledger_both: { label: 'Both (Customer & Supplier) Ledger', table: 'ledger_accounts', col: 'account_code', prefix: 'BTH', sep: '', digits: 6, shortName: 'short_name', nameCol: 'account_name' },
    account_group: { label: 'Ledger Group', table: 'account_groups', col: 'group_code', prefix: 'LGR', sep: '', digits: 6 },
    product: { label: 'Product', table: 'products', col: 'product_code', prefix: 'PRD', sep: '-', digits: 7, shortName: 'short_name', nameCol: 'product_name' },
    sub_ledger: { label: 'Sub Ledger', table: 'sub_ledgers', col: 'sub_ledger_code', prefix: 'SLG', sep: '', digits: 6 },
    product_group: { label: 'Product Group', table: 'product_groups', col: 'group_code', prefix: 'PGR', sep: '', digits: 6 },
    product_company: { label: 'Product Company', table: 'product_companies', col: 'company_code', prefix: 'PCO', sep: '', digits: 6 },
    product_category: { label: 'Product Category', table: 'product_categories', col: 'category_code', prefix: 'PCT', sep: '', digits: 6 },
    product_unit: { label: 'Product Unit', table: 'product_units', col: 'unit_code', prefix: 'UNT', sep: '', digits: 6 },
    ledger_category: { label: 'Ledger Category', table: 'ledger_categories', col: 'category_code', prefix: 'LCT', sep: '', digits: 6 },
    cost_center: { label: 'Cost Center', table: 'cost_centers', col: 'cost_center_code', prefix: 'CCT', sep: '', digits: 6 },
    profit_center: { label: 'Profit Center', table: 'profit_centers', col: 'profit_center_code', prefix: 'PCN', sep: '', digits: 6 },
    area: { label: 'Area', table: 'areas', col: 'area_code', prefix: 'ARA', sep: '', digits: 6 },
    route: { label: 'Route', table: 'routes', col: 'route_code', prefix: 'RUT', sep: '', digits: 6 },
    agent: { label: 'Salesman / Agent', table: 'salesman_agents', col: 'agent_code', prefix: 'AGT', sep: '', digits: 6 },
    transport: { label: 'Transport', table: 'transport_master', col: 'transport_code', prefix: 'TRN', sep: '', digits: 6 },
    billing_term: { label: 'Billing Term', table: 'billing_terms', col: 'term_code', prefix: 'BTM', sep: '', digits: 6 },
    business_unit: { label: 'Business Unit', table: 'business_units', col: 'unit_code', prefix: 'BUN', sep: '', digits: 6 },
    branch: { label: 'Branch', table: 'branches', col: 'branch_code', prefix: 'BRN', sep: '', digits: 6 },
    warehouse: { label: 'Warehouse', table: 'warehouses', col: 'warehouse_code', prefix: 'WHS', sep: '', digits: 6 },
    department: { label: 'Department', table: 'departments', col: 'department_code', prefix: 'DPT', sep: '', digits: 6 },
    designation: { label: 'Designation', table: 'designations', col: 'designation_code', prefix: 'DSG', sep: '', digits: 6 },
    bom_template: { label: 'BOM Template', table: 'bom_templates', col: 'template_code', prefix: 'BOM', sep: '', digits: 6 }
};

const clean = (v, max) => String(v || '').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, max);

/** effective format of every master (defaults + System Control overrides) */
async function formats(c, t) {
    const { data } = await c.from('system_control_settings').select('master_code_format').eq('tenant_id', t).maybeSingle();
    const saved = (data && data.master_code_format) || {};
    const useFy = saved.use_fy !== false;
    const out = {};
    for (const [k, m] of Object.entries(MASTERS)) {
        const s = saved[k] || {};
        out[k] = {
            key: k, label: m.label,
            prefix: clean(s.prefix, 6) || m.prefix,
            sep: s.sep === '-' || s.sep === '/' || s.sep === '' ? s.sep : m.sep,
            digits: Math.min(9, Math.max(3, parseInt(s.digits, 10) || m.digits)),
            // Total Length: the longest code allowed (year + separator + type + body)
            max_len: Math.min(40, Math.max(6, parseInt(s.max_len, 10) || (k === 'product' ? 30 : 15))),
            use_fy: useFy
        };
    }
    return out;
}

/** "2081/82" -> "8182", "2081-2082" -> "8182", none -> "" */
function fyCode(name) {
    const parts = String(name || '').match(/\d+/g) || [];
    if (!parts.length) return '';
    if (parts.length === 1) return parts[0].length >= 6 ? parts[0].slice(2, 4) + parts[0].slice(-2) : parts[0].slice(-4);
    return parts[0].slice(-2) + parts[1].slice(-2);
}
async function currentFy(c, t) {
    const { data } = await c.from('fiscal_years').select('fiscal_year_name').eq('tenant_id', t).eq('is_current', true).maybeSingle();
    return fyCode(data && data.fiscal_year_name);
}

const build = (f, fy, n) => `${f.use_fy ? fy : ''}${f.use_fy && fy ? f.sep : ''}${f.prefix}${String(n).padStart(f.digits, '0')}`;

async function readCounter(c, t, master, fy) {
    const { data } = await c.from('master_code_counters').select('last_no').eq('tenant_id', t).eq('master', master).eq('fy', fy).maybeSingle();
    return Number(data && data.last_no) || 0;
}

/** the code the next saved record will get (nothing is used up) */
async function preview(c, t, master) {
    if (!MASTERS[master]) throw Object.assign(new Error(`Unknown master "${master}"`), { status: 400 });
    const f = (await formats(c, t))[master];
    const fy = f.use_fy ? await currentFy(c, t) : '';
    return build(f, fy, (await readCounter(c, t, master, fy)) + 1);
}

/** take the next code (atomic in Postgres; read-modify-write when the function is missing) */
async function next(c, t, master) {
    if (!MASTERS[master]) throw Object.assign(new Error(`Unknown master "${master}"`), { status: 400 });
    const f = (await formats(c, t))[master];
    const fy = f.use_fy ? await currentFy(c, t) : '';
    const m = MASTERS[master];
    for (let attempt = 0; attempt < 5; attempt++) {
        let n;
        const r = await c.rpc('next_master_no', { p_tenant_id: t, p_master: master, p_fy: fy });
        if (!r.error && Number.isFinite(Number(r.data)) && Number(r.data) > 0) n = Number(r.data);
        else {                                   // migration 126 not run yet: plain read + write
            const { data: row } = await c.from('master_code_counters').select('last_no').eq('tenant_id', t).eq('master', master).eq('fy', fy).maybeSingle();
            n = (Number(row && row.last_no) || 0) + 1;
            const w = row ? await c.from('master_code_counters').update({ last_no: n }).eq('tenant_id', t).eq('master', master).eq('fy', fy)
                : await c.from('master_code_counters').insert({ tenant_id: t, master, fy, last_no: n });
            if (w.error) throw w.error;
        }
        const code = build(f, fy, n);
        if (code.length > f.max_len) throw new Error(`${f.label} code ${code} is longer than its Total Length (${f.max_len}) - System Control > Master Codes`);
        // a code typed in earlier (or an older format) may already hold this number - skip it
        const { data: taken } = await c.from(m.table).select('id').eq('tenant_id', t).eq(m.col, code).limit(1);
        if (!(taken || []).length) return code;
    }
    throw new Error('Could not find a free code - check System Control > Master Codes');
}

/** supabase-style wrapper so routes keep `const { data: codeRow, error: codeErr } = ...` */
async function nextRpc(c, t, master) {
    try { return { data: await next(c, t, master), error: null }; } catch (error) { return { data: null, error }; }
}

const initials = name => {
    const w = String(name || '').trim().toUpperCase().replace(/[^A-Z0-9\s]/g, ' ').split(/\s+/).filter(Boolean);
    if (!w.length) return '';
    return (w.length === 1 ? w[0].slice(0, 3) : w.map(x => x[0]).join('')).slice(0, 4);
};
/** suggested short name: initials + next free number for those initials */
async function shortNamePreview(c, t, master, name) {
    const m = MASTERS[master];
    if (!m || !m.shortName) return '';
    const ini = initials(name) || m.prefix;
    const { data } = await c.from(m.table).select(m.shortName).eq('tenant_id', t).ilike(m.shortName, `${ini}%`);
    let max = 0;
    (data || []).forEach(r => { const x = String(r[m.shortName] || '').slice(ini.length); if (/^\d+$/.test(x)) max = Math.max(max, Number(x)); });
    return `${ini}${String(max + 1).padStart(5, '0')}`;
}

/** the master code key of a ledger by its type (category_type of the ledger, else of its group) */
const ledgerMaster = categoryType => ({ sales: 'ledger_customer', customer: 'ledger_customer', purchase: 'ledger_supplier', supplier: 'ledger_supplier', both: 'ledger_both' }[categoryType] || 'ledger');

module.exports = { ledgerMaster, MASTERS, formats, preview, next, nextRpc, fyCode, currentFy, shortNamePreview, initials, build };
